In [2]:
import pandas as pd
from datetime import date
import sys

In [3]:
dfX_hist = pd.read_excel("./dfX_hist.xlsx")

In [4]:
dfX_hist.loc[:,("pos_call_finish","official_finish_position")].head()

   pos_call_finish  official_finish_position
0              5.0                       5.0
1              3.0                       3.0
2              6.0                       6.0
3              1.0                       1.0
4              2.0                       2.0

In [5]:
dfX_hist.loc[:,("final_tote_odds","official_finish_position")]

      final_tote_odds  official_finish_position
0                 5.5                       5.0
1                 8.5                       3.0
2                27.0                       6.0
3                 1.4                       1.0
4                 1.6                       2.0
5                21.4                       4.0
6                13.1                       7.0
7                 3.2                       2.0
8                15.8                       3.0
9                 1.9                       6.0
10               13.5                       5.0
11                3.0                       1.0
12                2.9                       4.0
13                5.1                       1.0
14               15.5                       3.0
15               14.1                       6.0
16                3.2                       5.0
17                4.1                       2.0
18                1.0                       4.0
19                NaN                       NaN
20                2.5                       4.0
21               10.7                       2.0
22                1.8                       1.0
23               10.1                       7.0
24               11.6                       5.0
25                7.8                       3.0
26                3.7                       6.0
27               20.5                       7.0
28                1.8                       3.0
29                5.1                       2.0
...               ...                       ...
7376              NaN                       NaN
7377              NaN                       NaN
7378              9.6                       5.0
7379             15.5                       3.0
7380              2.7                       6.0
7381              9.1                       1.0
7382              1.7                       2.0
7383              5.9                       7.0
7384              4.9                       4.0
7385              NaN                       NaN
7386              3.4                       4.0
7387             21.1                       3.0
7388              0.9                       2.0
7389              1.8                       1.0
7390             15.1                       5.0
7391              6.1                       5.0
7392             24.3                       8.0
7393              3.2                       4.0
7394              1.2                       1.0
7395             14.5                       7.0
7396             25.7                       3.0
7397              6.6                       2.0
7398              8.9                       6.0
7399              NaN                       NaN
7400              3.8                       2.0
7401              8.7                       3.0
7402              1.3                       1.0
7403              3.7                       4.0
7404              9.5                       5.0
7405              4.0                       6.0

[7406 rows x 2 columns]

In [6]:
dfX_hist['x8is_favorate_odds'] = dfX_hist.groupby('race_id')['final_tote_odds'].transform(lambda x: x==x.min())

In [7]:
dfX_hist['x8is_favorate_win'] = dfX_hist.transform(lambda x: x["x8is_favorate_odds"]==True and x["official_finish_position"]==1, axis=1)

In [8]:
dfX_hist['x8is_favorate_place'] = dfX_hist.transform(lambda x: x["x8is_favorate_odds"]==True and x["official_finish_position"]==2, axis=1)

In [9]:
dfX_hist['x8is_favorate_show'] = dfX_hist.transform(lambda x: x["x8is_favorate_odds"]==True and x["official_finish_position"]==3, axis=1)

In [10]:
dfX_hist['x8is_favorate_otb'] = dfX_hist.transform(lambda x: x["x8is_favorate_odds"]==True and x["official_finish_position"]>3, axis=1)

In [11]:
dfX_hist.to_csv("dfX_hist_new.csv")

In [12]:
dfX_hist_new = pd.read_csv("dfX_hist_new.csv")

In [13]:
dfX_hist_new["x8is_favorate_otb"]

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9        True
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18       True
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
7376    False
7377    False
7378    False
7379    False
7380    False
7381    False
7382    False
7383    False
7384    False
7385    False
7386    False
7387    False
7388    False
7389    False
7390    False
7391    False
7392    False
7393    False
7394    False
7395    False
7396    False
7397    False
7398    False
7399    False
7400    False
7401    False
7402    False
7403    False
7404    False
7405    False
Name: x8is_favorate_otb, Length: 7406, dtype: bool